<?php

namespace MinimalContactForm\Blocks;

use MinimalContactForm\Public\FormRenderer;

/**
 * Contact Form Block
 *
 * Registers and renders the Gutenberg block for the contact form.
 * Supports block-specific overrides for theme/styling and privacy mode
 * while using global settings for fields and email configuration.
 *
 * @since 1.0.0
 */
class ContactFormBlock
{
    /**
     * Plugin version
     *
     * @var string
     */
    private $version;

    /**
     * Form renderer instance
     *
     * @var FormRenderer
     */
    private $form_renderer;

    /**
     * Constructor
     *
     * @param string $version Plugin version
     */
    public function __construct($version)
    {
        $this->version = $version;
        $this->form_renderer = new FormRenderer($version);
    }

    /**
     * Register the block type
     *
     * @since 1.0.0
     */
    public function register()
    {
        $plugin_dir = dirname(dirname(dirname(__FILE__)));

        register_block_type(
            $plugin_dir . '/blocks/contact-form',
            [
                'render_callback' => [$this, 'render_block'],
            ]
        );

        // Enqueue theme CSS files for editor (after block registration)
        add_action('enqueue_block_editor_assets', [$this, 'enqueue_editor_assets']);
    }

    /**
     * Enqueue editor assets (theme CSS files)
     *
     * Preloads theme CSS content and passes it to JavaScript for inline injection.
     * Base CSS (style.css) is loaded via block.json.
     * Blocks inherit the global theme by default.
     *
     * @since 1.0.0
     */
    public function enqueue_editor_assets()
    {
        // Get global settings
        $options = get_option('mcf_options');
        $global_theme = $options['styling']['theme_preset'] ?? 'default';
        $global_custom_css = $options['styling']['custom_css'] ?? '';

        // Read theme CSS files
        $theme_css_contents = [];

        // Read all theme CSS files
        $themes = ['default', 'modern', 'minimal'];
        foreach ($themes as $theme) {
            $theme_path = plugin_dir_path(dirname(dirname(__FILE__))) . 'assets/public/css/themes/' . $theme . '.css';
            if (file_exists($theme_path)) {
                $theme_css_contents[$theme] = file_get_contents($theme_path);
            }
        }

        // Pass preloaded CSS content to JavaScript
        // Script handle is auto-generated by WordPress from block name: mcf/contact-form -> mcf-contact-form-editor-script
        wp_localize_script(
            'mcf-contact-form-editor-script',
            'mcfBlockEditor',
            [
                'previewCSS' => [
                    'themes' => $theme_css_contents,
                    'custom' => $global_custom_css,
                ],
                'globalTheme' => $global_theme,
            ]
        );
    }

    /**
     * Render the block
     *
     * @since 1.0.0
     * @param array $attributes Block attributes
     * @param string $content Block content (unused for dynamic blocks)
     * @param object $block Block instance
     * @return string Block HTML
     */
    public function render_block($attributes, $content = '', $block = null)
    {
        // Merge block attributes with global settings
        $merged_settings = $this->merge_settings($attributes);

        // Enqueue block-specific theme CSS (only if different from global)
        $this->enqueue_block_theme_css($merged_settings);

        // Render form with merged settings
        $output = $this->form_renderer->render_with_options($merged_settings);

        // Generate unique form ID for multiple blocks on same page
        $form_id = 'mcf-form-' . uniqid();
        $output = str_replace(
            'id="minimal-contact-form"',
            'id="' . esc_attr($form_id) . '"',
            $output
        );

        return $output;
    }

    /**
     * Enqueue block-specific theme CSS
     *
     * Only enqueues CSS if block theme differs from global theme.
     * Uses wp_enqueue_style to properly handle dependencies.
     *
     * @since 1.0.0
     * @param array $settings Merged settings for this block
     */
    private function enqueue_block_theme_css($settings)
    {
        static $block_counter = 0;
        $block_counter++;

        $global_options = get_option('mcf_options');
        $global_styling = $global_options['styling'] ?? [];
        $block_styling = $settings['styling'] ?? [];

        $global_theme = $global_styling['theme_preset'] ?? 'default';
        $block_theme = $block_styling['theme_preset'] ?? 'default';
        $block_custom_css = $block_styling['custom_css'] ?? '';
        $block_primary_color = $block_styling['primary_color'] ?? '';

        // Check if block differs from global
        $theme_differs = ($block_theme !== $global_theme);
        $has_block_primary_color = !empty($block_primary_color) && ($block_primary_color !== ($global_styling['primary_color'] ?? ''));

        if (!$theme_differs && !$has_block_primary_color) {
            // Block uses global settings, rely on Frontend::enqueue_styles()
            return;
        }

        // Block has different theme - enqueue it
        if ($theme_differs && $block_theme !== 'custom') {
            $theme_handle = 'mcf-block-theme-' . $block_counter;
            $theme_path = plugin_dir_path(dirname(dirname(__FILE__))) . 'assets/public/css/themes/' . $block_theme . '.css';

            if (file_exists($theme_path)) {
                wp_enqueue_style(
                    $theme_handle,
                    plugin_dir_url(dirname(dirname(__FILE__))) . 'assets/public/css/themes/' . $block_theme . '.css',
                    ['mcf-contact-form-style'],  // Depends on block.json's style
                    filemtime($theme_path)
                );

                // Add primary color override if set
                if ($has_block_primary_color) {
                    wp_add_inline_style($theme_handle, $this->generate_primary_color_css($block_primary_color));
                }
            }
        } elseif ($theme_differs && $block_theme === 'custom' && !empty($block_custom_css)) {
            // Custom theme with custom CSS
            $custom_handle = 'mcf-block-custom-' . $block_counter;
            wp_register_style($custom_handle, false, ['mcf-contact-form-style'], $this->version);
            wp_enqueue_style($custom_handle);
            wp_add_inline_style($custom_handle, $block_custom_css);

            // Add primary color override if set
            if ($has_block_primary_color) {
                wp_add_inline_style($custom_handle, $this->generate_primary_color_css($block_primary_color));
            }
        } elseif (!$theme_differs && $has_block_primary_color) {
            // Same theme but different primary color
            $color_handle = 'mcf-block-color-' . $block_counter;
            wp_register_style($color_handle, false, ['mcf-contact-form-style'], $this->version);
            wp_enqueue_style($color_handle);
            wp_add_inline_style($color_handle, $this->generate_primary_color_css($block_primary_color));
        }
    }

    /**
     * Generate primary color override CSS
     *
     * @since 1.0.0
     * @param string $color Hex color value
     * @return string CSS rules
     */
    private function generate_primary_color_css($color)
    {
        // Calculate hover color (20% darker)
        $hover_color = $this->adjust_brightness($color, -20);

        // Calculate contrast color for text
        $text_color = $this->get_contrast_color($color);
        $text_hover_color = $this->get_contrast_color($hover_color);

        return "
.mcf-form[data-theme-variant=\"light\"],
.mcf-form[data-theme-variant=\"dark\"] {
    --mcf-button-background-color: {$color} !important;
    --mcf-button-background-hover-color: {$hover_color} !important;
    --mcf-button-color: {$text_color} !important;
    --mcf-button-hover-color: {$text_hover_color} !important;
    --mcf-checkbox-color: {$color} !important;
}";
    }

    /**
     * Adjust brightness of a hex color
     *
     * @param string $hex Hex color
     * @param int $steps Brightness adjustment (-255 to 255)
     * @return string Adjusted hex color
     */
    private function adjust_brightness($hex, $steps)
    {
        $hex = ltrim($hex, '#');
        $r = hexdec(substr($hex, 0, 2));
        $g = hexdec(substr($hex, 2, 2));
        $b = hexdec(substr($hex, 4, 2));

        $r = max(0, min(255, $r + $steps));
        $g = max(0, min(255, $g + $steps));
        $b = max(0, min(255, $b + $steps));

        return \sprintf('#%02x%02x%02x', $r, $g, $b);
    }

    /**
     * Get contrast color (black or white) for given background
     *
     * @param string $hex Background hex color
     * @return string '#000000' or '#ffffff'
     */
    private function get_contrast_color($hex)
    {
        $hex = ltrim($hex, '#');
        $r = hexdec(substr($hex, 0, 2)) / 255;
        $g = hexdec(substr($hex, 2, 2)) / 255;
        $b = hexdec(substr($hex, 4, 2)) / 255;

        // Calculate relative luminance (WCAG 2.0)
        $r = $r <= 0.03928 ? $r / 12.92 : pow(($r + 0.055) / 1.055, 2.4);
        $g = $g <= 0.03928 ? $g / 12.92 : pow(($g + 0.055) / 1.055, 2.4);
        $b = $b <= 0.03928 ? $b / 12.92 : pow(($b + 0.055) / 1.055, 2.4);

        $luminance = 0.2126 * $r + 0.7152 * $g + 0.0722 * $b;

        return $luminance > 0.5 ? '#000000' : '#ffffff';
    }

    /**
     * Merge block attributes with global settings
     *
     * Priority: Block attributes > Global settings > Defaults
     *
     * @since 1.0.0
     * @param array $attributes Block attributes
     * @return array Merged settings
     */
    private function merge_settings($attributes)
    {
        $global_options = get_option('mcf_options');

        // Start with global options
        $merged = $global_options;

        // Override styling if block has custom values
        if (!empty($attributes['theme']) || !empty($attributes['variant']) ||
            !empty($attributes['primaryColor']) || !empty($attributes['customCSS'])) {

            $merged['styling'] = [
                'theme_preset' => !empty($attributes['theme'])
                    ? $attributes['theme']
                    : $global_options['styling']['theme_preset'],
                'variant' => !empty($attributes['variant'])
                    ? $attributes['variant']
                    : $global_options['styling']['variant'],
                'primary_color' => !empty($attributes['primaryColor'])
                    ? $attributes['primaryColor']
                    : ($global_options['styling']['primary_color'] ?? ''),
                'custom_css' => !empty($attributes['customCSS'])
                    ? $attributes['customCSS']
                    : ($global_options['styling']['custom_css'] ?? ''),
            ];
        }

        // Override privacy mode if block has custom value
        if (!empty($attributes['privacyMode'])) {
            $merged['fields']['field_groups']['gdpr']['mode'] = $attributes['privacyMode'];
        }

        return $merged;
    }
}
