<?php

namespace MinimalContactForm\Blocks;


// Prevent direct file access
if (!defined('ABSPATH')) {
    exit;
}
use MinimalContactForm\Public\FormRenderer;

/**
 * Contact Form Block
 *
 * Registers and renders the Gutenberg block for the contact form.
 * Supports block-specific overrides for theme/styling and privacy mode
 * while using global settings for fields and email configuration.
 *
 * @since 1.0.0
 */
class ContactFormBlock
{
    /**
     * Plugin version
     *
     * @var string
     */
    private $version;

    /**
     * Form renderer instance
     *
     * @var FormRenderer
     */
    private $form_renderer;

    /**
     * Constructor
     *
     * @param string $version Plugin version
     */
    public function __construct($version)
    {
        $this->version = $version;
        $this->form_renderer = new FormRenderer($version);
    }

    /**
     * Register the block type
     *
     * @since 1.0.0
     */
    public function register()
    {
        $plugin_dir = dirname(dirname(dirname(__FILE__)));

        register_block_type(
            $plugin_dir . '/blocks/contact-form',
            [
                'render_callback' => [$this, 'render_block'],
            ]
        );

        // Enqueue theme CSS files for editor (after block registration)
        add_action('enqueue_block_editor_assets', [$this, 'enqueue_editor_assets']);
    }

    /**
     * Enqueue editor assets (theme CSS files)
     *
     * Preloads theme CSS content and passes it to JavaScript for inline injection.
     * Base CSS (style.css) is loaded via block.json.
     * Blocks inherit the global theme by default.
     *
     * @since 1.0.0
     */
    public function enqueue_editor_assets()
    {
        // Get global settings
        $options = get_option('mcf_options');
        $global_theme = $options['styling']['theme_preset'] ?? 'default';
        $global_custom_css = $options['styling']['custom_css'] ?? '';

        // Read theme CSS files
        $theme_css_contents = [];

        // Read all theme CSS files
        $themes = ['default', 'modern', 'minimal'];
        foreach ($themes as $theme) {
            $theme_path = plugin_dir_path(dirname(dirname(__FILE__))) . 'assets/public/css/themes/' . $theme . '.css';
            if (file_exists($theme_path)) {
                $theme_css_contents[$theme] = file_get_contents($theme_path);
            }
        }

        // Pass preloaded CSS content to JavaScript
        // Script handle is auto-generated by WordPress from block name: mcf/contact-form -> mcf-contact-form-editor-script
        wp_localize_script(
            'mcf-contact-form-editor-script',
            'mcfBlockEditor',
            [
                'previewCSS' => [
                    'themes' => $theme_css_contents,
                    'custom' => $global_custom_css,
                ],
                'globalTheme' => $global_theme,
                'privacyPage' => [
                    'exists' => (bool) get_option('wp_page_for_privacy_policy'),
                    'url' => get_privacy_policy_url() ?: '',
                ],
            ]
        );

        // Set script translations for block editor
        wp_set_script_translations(
            'mcf-contact-form-editor-script',
            'mcf',
            plugin_dir_path(dirname(dirname(__FILE__))) . 'languages'
        );
    }

    /**
     * Render the block
     *
     * @since 1.0.0
     * @param array $attributes Block attributes
     * @param string $content Block content (unused for dynamic blocks)
     * @param object $block Block instance
     * @return string Block HTML
     */
    public function render_block($attributes, $content = '', $block = null)
    {
        // Merge block attributes with global settings
        $merged_settings = $this->merge_settings($attributes);

        // Generate unique block ID
        static $block_counter = 0;
        $block_counter++;
        $block_id = 'mcf-block-' . $block_counter;

        // Enqueue inline CSS for this block
        $this->enqueue_block_inline_css($merged_settings['styling'], $block_id);

        // Render form with merged settings (skip CSS enqueue since we handle it here)
        // Note: FormRenderer will generate its own instance ID (e.g., mcf-form-1)
        // which won't match our block_id (e.g., mcf-block-1), so we need to replace it
        $output = $this->form_renderer->render_with_options($merged_settings, true);

        // Replace FormRenderer's instance ID with our block ID
        // FormRenderer generates IDs like "mcf-form-1", we need "mcf-block-1"
        $output = preg_replace(
            '/id="mcf-form-\d+"/',
            'id="' . esc_attr($block_id) . '"',
            $output,
            1  // Only replace first occurrence
        );

        return $output;
    }

    /**
     * Enqueue inline CSS for this block instance
     *
     * Uses CSSService to consolidate all CSS layers (base, theme, custom, primary color)
     * and inject them inline for this specific block instance.
     *
     * @since 1.0.0
     * @param array $styling Styling settings
     * @param string $block_id Unique block identifier (e.g., 'mcf-block-1')
     */
    private function enqueue_block_inline_css($styling, $block_id)
    {
        // Use CSSService to consolidate CSS
        $inline_css = \MinimalContactForm\Services\CSSService::consolidate_inline_css(
            $styling,
            $block_id
        );

        // Register inline-only style
        // Handle will be: mcf-block-1, mcf-block-2, etc.
        wp_register_style($block_id, false, [], $this->version);
        wp_enqueue_style($block_id);
        wp_add_inline_style($block_id, $inline_css);
    }

    /**
     * Merge block attributes with global settings
     *
     * Priority: Block attributes > Global settings > Defaults
     *
     * @since 1.0.0
     * @param array $attributes Block attributes
     * @return array Merged settings
     */
    private function merge_settings($attributes)
    {
        $global_options = get_option('mcf_options');

        // Start with global options
        $merged = $global_options;

        // Override styling if block has custom values
        if (!empty($attributes['theme']) || !empty($attributes['variant']) ||
            !empty($attributes['primaryColor']) || !empty($attributes['customCSS'])) {

            $merged['styling'] = [
                'theme_preset' => !empty($attributes['theme'])
                    ? $attributes['theme']
                    : $global_options['styling']['theme_preset'],
                'variant' => !empty($attributes['variant'])
                    ? $attributes['variant']
                    : $global_options['styling']['variant'],
                'primary_color' => !empty($attributes['primaryColor'])
                    ? $attributes['primaryColor']
                    : ($global_options['styling']['primary_color'] ?? ''),
                'custom_css' => !empty($attributes['customCSS'])
                    ? $attributes['customCSS']
                    : ($global_options['styling']['custom_css'] ?? ''),
            ];
        }

        // Override privacy mode if block has custom value
        if (!empty($attributes['privacyMode'])) {
            $merged['fields']['field_groups']['gdpr']['mode'] = $attributes['privacyMode'];
        }

        return $merged;
    }
}
